/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

// @author : 1923636 Ellaine Fontamillas

import AllUsers.FeedbackClass;
import AllUsers.UserDB;
import java.time.LocalDate;
import javax.swing.JOptionPane;

public class AdminSendFeedback extends javax.swing.JFrame {
    public static AdminSendFeedback afb = new AdminSendFeedback();
    public static AdminMain am = new AdminMain();
    //public static CitizenForm cf = new CitizenForm();
    /**
     * Creates new form CitizenFeedback
     */
    public AdminSendFeedback() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblFeedbackNo = new javax.swing.JLabel();
        lblFeedbackTitle = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        lblFeedbackType = new javax.swing.JLabel();
        txtFeedbackNo = new java.awt.TextField();
        txtFeedbackTitle = new java.awt.TextField();
        lblDetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescription = new javax.swing.JTextArea();
        btnSendFeedback = new javax.swing.JButton();
        btnGoToHome = new javax.swing.JButton();
        cbxDepartment = new javax.swing.JComboBox<>();
        cboxType = new javax.swing.JComboBox<>();
        lblPassportID = new javax.swing.JLabel();
        txtPassportID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Send Feedback - Lesotho Government Feeedback Services");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Send Feedback");

        lblFeedbackNo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFeedbackNo.setForeground(new java.awt.Color(255, 255, 255));
        lblFeedbackNo.setText("Feedback No");

        lblFeedbackTitle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFeedbackTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblFeedbackTitle.setText("Feedback Title");

        lblDepartment.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartment.setText("Department");

        lblFeedbackType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFeedbackType.setForeground(new java.awt.Color(255, 255, 255));
        lblFeedbackType.setText("Type");

        txtFeedbackNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeedbackNoActionPerformed(evt);
            }
        });

        lblDetails.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblDetails.setText("Description");

        txtAreaDescription.setColumns(20);
        txtAreaDescription.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescription);

        btnSendFeedback.setText("Submit");
        btnSendFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendFeedbackActionPerformed(evt);
            }
        });

        btnGoToHome.setText("Go Back");
        btnGoToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToHomeActionPerformed(evt);
            }
        });

        cbxDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "National manpower development secretariat", "National curriculum development", "National environment secretariat", "Correctional Services ", "Department of water affairs", "Directorate of dispute prevention", "Directorate on corruption", "District Administration – DA Office", "Global fund coordinating national aids", "High Court" }));

        cboxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select type of feedback", "Complaint", "Suggestion", "Comment" }));

        lblPassportID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPassportID.setForeground(new java.awt.Color(255, 255, 255));
        lblPassportID.setText("Passport ID");

        txtPassportID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDepartment)
                    .addComponent(lblFeedbackTitle)
                    .addComponent(lblFeedbackType)
                    .addComponent(lblFeedbackNo)
                    .addComponent(lblPassportID))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboxType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxDepartment, 0, 220, Short.MAX_VALUE)
                    .addComponent(txtFeedbackNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFeedbackTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassportID))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblDetails)
                            .addGap(259, 259, 259))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1)
                            .addGap(36, 36, 36)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSendFeedback)
                        .addGap(31, 31, 31)
                        .addComponent(btnGoToHome)
                        .addGap(45, 45, 45))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassportID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassportID))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFeedbackNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFeedbackNo))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFeedbackTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFeedbackTitle))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDepartment))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFeedbackType)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSendFeedback)
                            .addComponent(btnGoToHome))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFeedbackNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeedbackNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeedbackNoActionPerformed

    private int checkDep()
    { 
        String dep = cbxDepartment.getSelectedItem().toString();
        switch(dep)
        {
            case "National manpower development secretariat":
                return 2233;
            case "National curriculum development":
                return 2244;
            case "National environment secretariat":
                    return 2255;
            case "Correctional Services ":
                return 2266;
            case "Department of water affairs":
                return 2277;
            case "Directorate of dispute prevention":
                return 2288;
            case "Directorate on corruption":
                return 2299;
            case "District Administration – DA Office":
                    return 2287;
            case "Global fund coordinating national aids":
                return 2276;
            case "High Court":
                return 2265;
            default:
                return 0;
                   
        }
            
    }
    
    private int getMinistryNo()
    {
        int dep = checkDep();
        switch(dep)
        {
            case 2233:
                return 56410;
            case 2244:
                return 64561;
            case 2255:
                return 95917;
            case 2266:
                return 64165;
            case 2277:
                return 84651;
            case 2288:
                return 85451;
            case 2299:
                return 85451;
            case 2287:
                return 56410;
            case 2276:
                return 65564;
            case 2265:
                return 85451;
            default:
                return 0; 
        }
    }
    
    private void btnSendFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendFeedbackActionPerformed
        // TODO add your handling code here:
          try
        {
            // Default 
            
            String status = "submitted";
            String assignee = "Clerk";
            LocalDate dt = LocalDate.now();
            String dateCreated = dt.toString();
            
            
            // Values from the user
            
            String pid = afb.txtPassportID.getText();
            int id = Integer.parseInt(afb.txtFeedbackNo.getText());
            String title = afb.txtFeedbackTitle.getText();
            String department = afb.cbxDepartment.getSelectedItem().toString();
            String type = afb.cboxType.getSelectedItem().toString();
            String description = afb.txtAreaDescription.getText();
            
            int departmentNo = checkDep();
            int MinisterialNo = getMinistryNo();
            // Send input to Class THEN Class with JDBC Driver
            FeedbackClass fb = new FeedbackClass(title,status,department,type,assignee,description,id,dateCreated,pid,departmentNo,MinisterialNo);
            UserDB.UserSendFeedback(fb);
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());//"An error occured! You cannot submit the form empty. \n Ensure that the data types are correct","Error Message",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSendFeedbackActionPerformed

    private void btnGoToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToHomeActionPerformed
        // TODO add your handling code here:
        
        int input = JOptionPane.showConfirmDialog(null, "Are you sure you want to leave this page?","Confirm Message",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(input == 0)
        {
            this.setVisible(false);
            am.setVisible(true);
        }
        else 
            JOptionPane.showMessageDialog(null, "You have opted to stay");
    }//GEN-LAST:event_btnGoToHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSendFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSendFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSendFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSendFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                afb.setVisible(true);
                afb.setResizable(false);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoToHome;
    private javax.swing.JButton btnSendFeedback;
    private javax.swing.JComboBox<String> cboxType;
    private javax.swing.JComboBox<String> cbxDepartment;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblFeedbackNo;
    private javax.swing.JLabel lblFeedbackTitle;
    private javax.swing.JLabel lblFeedbackType;
    private javax.swing.JLabel lblPassportID;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtAreaDescription;
    private java.awt.TextField txtFeedbackNo;
    private java.awt.TextField txtFeedbackTitle;
    private javax.swing.JTextField txtPassportID;
    // End of variables declaration//GEN-END:variables
}
